
# Macro file for the visualization of the PADME experiment
#ModifySAC
#
# Sets some default verbose
#
/control/verbose 1
/run/verbose 1
/tracking/verbose 0

# General run settings

# How often event printout is shown
#/settings/PrintOutFrequency 100

# Automatically generate random seeds using system time
# If disabled, user must set environment variables PADME_SEED1 and PADME_SEED2
#/settings/AutomaticRandomSeed true

# Turbo mode kills low energy particles to speed up rough detector studies
# ENABLE ONLY IF YOU KNOW WHAT YOU ARE DOING!
#/settings/TurboModeEnable false

# Set verbose level for TurboMode. If >=10 show all killed particles
#/settings/TurboMode/Verbose 0

# Turbo mode thresholds for e+,e-,gamma,neutron
# Particles will be killed if their kinetic energy is below threshold
#/settings/TurboMode/KillEnergyPositron 10. MeV
#/settings/TurboMode/KillEnergyElectron 10. MeV
#/settings/TurboMode/KillEnergyGamma     1. MeV
#/settings/TurboMode/KillEnergyNeutron  10. MeV

# RootIO settings

# Output root file with MC hits
#/output/DataFileName MCData.root

# Output root file with analysis histograms/ntuple
#/output/HistoFileName UBTF.root

# Disable/enable SAC/ECal analysis (WARNING! For SAC see command documentation)
#/analysis/DisableSACAnalysis true
/analysis/DisableECalAnalysis true
			      
# Disable/enable saving to Fast analysis Tree U102
# uses conditions on ECal Energy, SAC energy, Hit in the Veto
/analysis/SaveEcal  false
/analysis/SaveVeto  false
/analysis/SaveSAC   true

# Enable IO for single detectors
#/output/EnableDetectorIO Target:D
#/output/EnableDetectorIO PVeto:HD
#/output/EnableDetectorIO EVeto:HD
#/output/EnableDetectorIO HEPVeto:HD
#/output/EnableDetectorIO ECal:D
#/output/EnableDetectorIO SAC:D
#/output/EnableDetectorIO TPix:D

# Disable IO for single detectors
/output/DisableDetectorIO Target
/output/DisableDetectorIO PVeto
/output/DisableDetectorIO EVeto
/output/DisableDetectorIO HEPVeto
/output/DisableDetectorIO ECal
#/output/DisableDetectorIO SAC
/output/DisableDetectorIO TPix

# Detector settings

#/Detector/VerboseLevel 0

#/Detector/EnableSubDetector ECal
/Detector/EnableSubDetector Target
/Detector/EnableSubDetector SAC
#Detector/EnableSubDetector PVeto
#/Detector/EnableSubDetector EVeto
#/Detector/EnableSubDetector HEPVeto
#/Detector/EnableSubDetector TDump
#/Detector/EnableSubDetector TPix

#/Detector/EnableStructure Magnet
#/Detector/EnableStructure Chamber
#/Detector/EnableStructure BeamLine

/Detector/DisableSubDetector ECal
#/Detector/DisableSubDetector Target
#/Detector/DisableSubDetector SAC
/Detector/DisableSubDetector PVeto
/Detector/DisableSubDetector EVeto
/Detector/DisableSubDetector HEPVeto
/Detector/DisableSubDetector TDump
/Detector/DisableSubDetector TPix

/Detector/DisableStructure Magnet
/Detector/DisableStructure Chamber
#/Detector/DisableStructure BeamLine

#/Detector/WorldIsAir
#/Detector/WorldIsVacuum

#/Detector/SetMagnetVisible
#/Detector/SetMagnetInvisible

#/Detector/SetChamberVisible
#/Detector/SetChamberInvisible

#/Detector/SetBeamLineVisible
#/Detector/SetBeamLineInvisible

#/Detector/EnableMagneticField
/Detector/DisableMagneticField
#/Detector/SetMagneticFieldValue 0.4542 tesla

#/Detector/CrossMagneticVolume internal
#/Detector/CrossMagneticVolume external

#/Detector/SetMagneticVolumeVisible
/Detector/SetMagneticVolumeInvisible


/Detector/SAC/VerboseLevel 3
/Detector/SAC/NRows   10
/Detector/SAC/NCols   10
/Detector/SAC/NLayers 4	
/Detector/SAC/CrystalSize 2. cm
/Detector/SAC/CrystalLength 5. cm
#/Detector/SAC/CrystalGap 50. um
#/Detector/SAC/CrystalCoating 100. um
#/Detector/SAC/FrontFaceZ 300. cm


# Beam setup

# Primary positrons setup (default PADMEMC configuration)
# Particle 0: gamma, 1 neutron
/beam/particle 1

/beam/n_e+_per_bunch 1
#/beam/n_e+_poisson_on true
#/beam/bunch_structure_on true
#/beam/bunch_time_length 250. ns
#/beam/ubunch_time_length 150. ps
#/beam/ubunch_time_delay 350. ps
/beam/position_x 1. cm
#/beam/position_y 0. cm
/beam/position_z -90. cm
#/beam/position_spread_on true
#/beam/position_x_spread 1. mm
#/beam/position_y_spread 1. mm
/beam/momentum 25000 MeV
/beam/momentum_spread_on false
#/beam/momentum_spread 5.45 MeV
/beam/direction 0. 0. 1.
/beam/emittance_on false
#/beam/emittance_x 1. mrad
#/beam/emittance_y 1. mrad
#/beam/uboson_mass 22. MeV
#/beam/calibration false
#/beam/calib_energy 50. MeV
#/beam/calib_x 14. cm
#/beam/calib_y 14. cm
#/beam/calib_radius 1. cm

#
# Calibration run setup: single 50MeV photon pointing to a spot on ECal front face
#/beam/calibration true
#/beam/calib_energy 50. MeV
#/beam/calib_x 14. cm
#/beam/calib_y 14. cm
#/beam/calib_radius 1. cm

# Create detectors and initialize run
/run/initialize

# Use this open statement to create an OpenGL view:
/vis/open OGL 600x600-0+0

# Use this open statement to create a .prim file suitable for viewing in DAWN:
#/vis/open DAWNFILE

# Use this open statement to create a .heprep file suitable for viewing in HepRApp:
#/vis/open HepRepFile
#/vis/open HepRepXML
#/vis/heprep/setEventNumberSuffix -0001
#/vis/scene/add/trajectories rich

# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE

# Disable auto refresh and quieten vis messages whilst scene and trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors

# Draw geometry:
/vis/drawVolume
#/geometry/test/grid_test true

#/vis/viewer/set/viewpointVector 0. 10. 0.

# Choose viewpoint
# Side view
#/vis/viewer/set/viewpointThetaPhi -90. 0. deg
# Top view
#/vis/viewer/set/viewpointThetaPhi 90. 90. deg
# Front view
/vis/viewer/set/viewpointThetaPhi 0. 0. deg
# Back view
#/vis/viewer/set/viewpointThetaPhi 180. 0. deg

# Specify zoom value:
/vis/viewer/zoom 1.8

# Specify style (surface or wireframe):
/vis/viewer/set/style wireframe
#/vis/viewer/set/style surface

# Draw coordinate axes:
/vis/scene/add/axes 0 0 0 1 m

# Decorations
/vis/set/textColour green
/vis/set/textLayout right
/vis/scene/add/text2D 0.9 -.9 24 ! ! KLEVER SAC
/vis/set/textLayout    # Revert to normal (left adjusted) layout
/vis/set/textColour    # Revert to default text colour (blue)
/vis/scene/add/eventID # Drawn at end of event
/vis/scene/add/date    # Date stamp

# Draw smooth trajectories at end of event, showing trajectory points as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)

# Draw hits at end of event:
#/vis/scene/add/hits

# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma

# To invert the above, drawing all particles except gammas, keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true

# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e- blue

# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate

# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings

# Fix problem in visualizing some circular parts
/vis/viewer/set/lineSegmentsPerCircle 50

/vis/scene/endOfEventAction accumulate 10

/vis/viewer/flush

# Calo picture
 /vis/viewer/set/viewpointThetaPhi 45. 45.
 /vis/viewer/panTo -1 -0.9
 /vis/viewer/zoom 4.5

# Monitor picture
#/vis/viewer/panTo -0.5 0.
#/vis/viewer/set/viewpointThetaPhi 0. 0.
#/vis/viewer/zoom 50

# Only show tracks with p>1MeV
/vis/filtering/trajectories/create/attributeFilter
/vis/filtering/trajectories/attributeFilter-0/setAttribute IMag
/vis/filtering/trajectories/attributeFilter-0/addInterval 1. MeV 100000. MeV

#/run/beamOn 100	
